### ISSUE TITLE
Make errors, missing files mentioned in README

### ISSUE THREAD

**Issue by jessepfrancis** [01org/dptf#16]
I have a new laptop with Core i7 7th Gen, and since no Windows other than 10 work on 7th Gen Intel, I decided to switch completely to Linux.

I was going through all drivers for Windows that was given in the CD that came with Laptop, and there is one driver called "DPTF", which far as I read is not implemented in Linux Kernel.

Google took me to https://github.com/01org/dptf , where there's detailed instruction on how to compile the code, with minor glitches.

In light of that, 

1. Will getting it set up on Linux benefit me in any way?
2. If it does, from README.md of git, under instructions for Ubuntu (I'm using Linux Mint 18.1)

* (Step 5) <DPTF root>/DPTF/Sources/combined.xsl doesn't exist. Should I worry about it?
* >Run make under <DPTF root>/ESIF/Products/ESIF_UF/Linux to build
the esif_ufd executable.

   running make with that directory in focus gives a series of errors,

>`++++ 
++++ ESIF_UF x64 Release Linux GMIN=1
++++ 
gcc -c -Wno-multichar -Werror -fPIE -fPIC -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -fstack-protector-strong -m64  -I../../ESIF_UF/Sources -I../../ESIF_CM/Sources -I../../ESIF_WS/Sources -I../../ESIF_LIB/Sources -I../../../../Common -DESIF_ATTR_USER  -DESIF_ATTR_DAEMON -DESIF_ATTR_OS_LINUX -DESIF_ATTR_OS_LINUX_HAVE_READLINE  -DESIF_FEAT_OPT_ACTION_SYSFS -o ../../ESIF_UF/Sources/lin/main.o ../../ESIF_UF/Sources/lin/main.c
In file included from ../../../../Common/esif_ccb_sort.h:29:0,
                 from ../../../../Common/esif_ccb_file_lin_user.h:100,
                 from ../../../../Common/esif_ccb_file.h:28,
                 from ../../ESIF_CM/Sources/esif.h:198,
                 from ../../ESIF_UF/Sources/esif_uf.h:22,
                 from ../../ESIF_UF/Sources/lin/main.c:27:
../../../../Common/esif_ccb_file_lin_user.h: In function ‘esif_ccb_file_enum_first’:
../../../../Common/esif_ccb_sort_lin_user.h:60:48: error: implicit declaration of function ‘qsort_r’ [-Werror=implicit-function-declaration]
 #define esif_ccb_qsort(bas, num, siz, fn, ctx) qsort_r(bas, num, siz, fn, ctx)
                                                ^
../../../../Common/esif_ccb_file_lin_user.h:169:3: note: in expansion of macro ‘esif_ccb_qsort’
   esif_ccb_qsort(find_handle->files, find_handle->matches, sizeof(char *), esif
   ^
cc1: all warnings being treated as errors
Makefile:180: recipe for target '../../ESIF_UF/Sources/lin/main.o' failed
make: *** [../../ESIF_UF/Sources/lin/main.o] Error 1`

How to fix this?

**Comment by bbian** [comment]
Hi, this issue appears to be due to a recent GCC/GLibc update that is now fully conforming to GNU99 standard, therefore rendering the qsort_r() function obsolete. We will provide an update to the esif_ufd makefile to address this issue.

**Comment by jessepfrancis** [comment]
Forgot to mention. I fixed it by adding "-std=89" in CPPFLAGS (edited MAKEFILE)
